server:
  port: 8080
  servlet:
    context-path: /

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: ismasurance_db

logging:
  level:
    org:
      springframework:
        web: DEBUG

tokenSecret: WwwNdyesJxEQk6q3R7v9wNuI5gcxurWp

#spring.datasource.username=root
#spring.datasource.password=
#spring.datasource.url=jdbc:mysql://localhost:3306/udemy_curso_spring_react
#spring.jpa.ddl-auto=update

